---
# Clone New VM from template in Proxmox
- name: Cloning virtual machine from "{{ VM_template }}" with name "{{ VM_name }}"
  proxmox_kvm:
    api_user: "{{ vault_proxmox_user }}"
    api_token_id: "{{ vault_proxmox_token_id }}"
    api_token_secret: "{{ vault_proxmox_api_key }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ VM_name }}"
    node: "{{ proxmox_host }}"
    clone: "{{ VM_template }}"
    timeout: 300
  tags: provision,test

- name: Waiting to apply cloud init changes in disk
  wait_for:
    timeout: 5
  tags: provision

- name: starting new Virtual Machine to change IPv4 configuration, it is necessary
  proxmox_kvm:
    api_user: "{{ vault_proxmox_user }}"
    api_token_id: "{{ vault_proxmox_token_id }}"
    api_token_secret: "{{ vault_proxmox_api_key }}"
    api_host: "{{ proxmox_host }}"
    name: "{{ VM_name }}"
    node: "{{ proxmox_host }}"
    state: started
    timeout: 300
  register: wait
  tags: provision

- name: Waiting to start virtual server machine completely
  wait_for:
    timeout: 45
  when: wait.changed == true
  tags: provision

- debug:
    msg: "item.key {{ item.key }} item.value {{ item.value }} item.value.netmask {{ item.value.netmask }} item.value.vmbr {{ item.value.vmbr }}"
  with_dict: "{{ vars[VM_network] }}"
  tags: provision
