---
VM_template: "{{ os_template | default('CentOS-7-template') }}"
default_disk: virtio0
default_interface: net0
default_volume: /dev/vda
default_partition: 1
template_name: "{{ os_template | default('CentOS-7-template') }}"
vault_proxmox_user: "{{ proxmox_user }}"
vault_proxmox_token_id: "{{ proxmox_token_id }}"
vault_proxmox_api_key: "{{ proxmox_api_key }}"
vault_api_password: "{{ api_password }}"
proxmox_host: 192.168.0.250
vm_name_nt: "{{ VM_name }}"
initial_setup_user: tatux
initial_setup_password: "{{ vault_initial_setup_password }}"